name: 'Interdisciplinary Quantum Materials'
title: 'Interdisciplinary Quantum Materials'
description: 'We focus on the theory and simulation of quantum materials for energy-efficiency applications.'
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
#baseurl: 'https://nguyen-group.github.io'
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
google_analytics: 'UA-70667326-1'
disqus: 'demowebsite'
include:
  - _pages
permalink: '/:title/'
authors:
  nguyen:
    name: Nguyen Tuan Hung
    display_name: N. T. Hung
    gravatar: 69bfba362c993c163b38b0c09c529797
    email: 'hung@live.jp'
    web: 'https://nguyen-group.github.io/'
    twitter: 'https://twitter.com/tuanhung52'
    description: >-
      Hi, Iâ€™m Hung, and I write blogs because I love nature and science. I hope
      you like it.
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-admin
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: disabled
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
jekyll_admin:
  hidden_links: null
  homepage: ''
